# Generated by Django 5.2.8 on 2025-11-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopping',
            fields=[
                ('ProductId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=30)),
                ('Category', models.CharField(max_length=15)),
                ('Price', models.IntegerField()),
                ('ProductDescription', models.CharField(max_length=100)),
                ('Discount', models.IntegerField()),
                ('Retailer', models.CharField(max_length=10)),
            ],
        ),
    ]
